### ISSUE TITLE
front-end Página da Oferta

### ISSUE THREAD

**Issue by campolivre** [campolivre/plataforma#17]
Página que contém todas as informações da oferta para o perfil Comprador adquirir produtos na plataforma

### Tarefas
- [x] Área de Galeria de Fotos
- [x] Área de Video
- [x] Área de Mapa
- [x] Área da Descrição da Oferta
- [x] Área do CTA do Carrinho

**Comment by waltherneto** [comment]
Nesse commit é adicionada a página de oferta da plataforma Campo Livre ainda sem o _back-end_.

Foi alterado também a fonte da plataforma visto que a **Lato** estava dando problemas de legibilidade.
