### ISSUE TITLE
Calculadora de Preço

### ISSUE THREAD

**Issue by campolivre** [campolivre/plataforma#20]
Desenvolver a calculadora de preço dentro da página de cada oferta.

### TAREFAS
- [x] cada item de valor ser considerado um número
- [x] fazer os cálculos para apresentar o valor total
- [x] inserir o resultado em um array global

**Comment by waltherneto** [comment]
Foi desenvolvido a funcionalidade da calculadora dentro da página de oferta. Foram inseridas as seguintes funcionalidades:

• Controle via caixas de adição e subtração unitária
• Controle via input de texto
• Lógica de eventos onClick e onChange
• Lógica para não permitir que os valores sejam calculados além do permitido do estoque
• Não permitir caracteres não-numéricos no input de texto
• Atualização automática dos valores a partir da interação do usuário com os controles
