### ISSUE TITLE
Carrinho de Compras

### ISSUE THREAD

**Issue by campolivre** [campolivre/plataforma#22]
Inserir o carrinho de compras na área de **navegação principal** baseado na interação do usuário com a **página de oferta**

### Tarefas
- [x] inserir ícone de carrinho na navegação principal (desktop e mobile)
~~inserir um contador de itens no carrinho baseado na interação do usuário~~
~~criar um array global com as informações do carrinho~~

**Comment by waltherneto** [comment]
Inserido o carrinho de compras na barra de navegação da plataforma (desktop e mobile) para futura manipulação do _back-end_.

As ações de **(1) inserir um contador de itens no carrinho baseado na interação do usuário** e **(2) criar um array global com as informações do carrinho**, foram repassadas para o _back-end_.
